#!/bin/bash
suffix="dpc3_traces/"
a=1
p=52
while [ $a -lt 25 ]
do
    if [ $x -lt 5 ]
    then
    foo1=$(sed "${a}q;d" traces1);
    foo1=${foo1#$suffix}
    foo2=$(sed "${a}q;d" traces2);
    foo2=${foo2#$suffix}
    foo3=$(sed "${a}q;d" traces3);
    foo3=${foo3#$suffix}
    foo4=$(sed "${a}q;d" traces4);
    foo4=${foo4#$suffix}
    a=$((a+1))
        # ./run_4core.sh bimodal-no-spp_dev1-no-lru-4core 50 200 0  $foo1 $foo2 $foo3 $foo4  &
         echo $foo1-$foo2-$foo3-$foo4 
    x=$((x+1))     
    else
        x=0
        # ssh into new machine
        ssh jatindev@172.27.19.{$p}
        p=p+1

    fi
     
done

